# Site settings
title: Hazardous Waste Information Platform (HWIP) Help
# email: myemail@example.com
description: > # this means to ignore newlines until "baseurl:"
  Help documentation for Hazardous Waste Information Platform (HWIP) Help
baseurl: "/docs/" # the subpath of your site, e.g. /blog/
url: "https://usepa.github.io/hwip/" # the base hostname & protocol for your site
#twitter_username: 
#github_username: 

# Build settings
markdown: kramdown
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Defaults for front matter
# defaults:
#   - scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts" # applies to posts
#     values:
#       layout: "post"
#   - scope:
#       path: "" # an empty string here means all files in the project
#       type: "pages" # applies to pages
#     values:
#       layout: "page"
